blank_issues_enabled: false
contact_links:
  - name: D3ploy related issues
    url: https://github.com/7figurefortune/bolt.diy/issues/new/choose
    about: Report issues related to D3ploy
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other D3ploy users.
